//! FerroPHP scoreboard.
//!
//! Scans every `.phpt` test — our curated set in `tests/phpt/` plus the full
//! upstream corpus in `vendor/php-src/` if present — runs each against the
//! engine, compares output to the test's own `--EXPECT--` section, and writes a
//! `PROGRESS.md` summarising the pass-rate overall and by area.
//!
//! At this scale we do NOT list every test (there are ~18k). We bucket results
//! by area (per-extension, Zend, core) so the report stays readable.

use ferrophp::run;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

struct Phpt {
    file: String,
    expect: Option<String>,
    has_expectf: bool,
}

enum Outcome {
    Pass,
    Fail,
    Unsupported, // can't grade yet (e.g. --EXPECTF--, or no expected output)
}

/// [pass, fail, n/a, total]
type Tally = [usize; 4];

fn main() {
    let root = env!("CARGO_MANIFEST_DIR");
    let curated = Path::new(root).join("tests").join("phpt");
    let corpus = Path::new(root).join("vendor").join("php-src");

    // Gather (group, path) for every test.
    let mut tests: Vec<(String, PathBuf)> = Vec::new();
    let mut cu = Vec::new();
    collect_phpt(&curated, &mut cu);
    for p in cu {
        tests.push(("_curated (ours)".to_string(), p));
    }
    if corpus.exists() {
        let mut co = Vec::new();
        collect_phpt(&corpus, &mut co);
        for p in co {
            let g = group_of(&p);
            tests.push((g, p));
        }
    } else {
        eprintln!("(vendor/php-src not found — run scripts/fetch-corpus.sh for the full suite)");
    }

    let mut groups: BTreeMap<String, Tally> = BTreeMap::new();
    let mut overall: Tally = [0; 4];

    let n = tests.len();
    for (i, (group, path)) in tests.iter().enumerate() {
        let bytes = fs::read(path).unwrap_or_default();
        let text = String::from_utf8_lossy(&bytes);
        let t = parse_phpt(&text);
        let slot = groups.entry(group.clone()).or_insert([0; 4]);
        let idx = match evaluate(&t) {
            Outcome::Pass => 0,
            Outcome::Fail => 1,
            Outcome::Unsupported => 2,
        };
        slot[idx] += 1;
        slot[3] += 1;
        overall[idx] += 1;
        overall[3] += 1;
        if n > 2000 && i % 4000 == 0 && i > 0 {
            eprintln!("  …{i}/{n}");
        }
    }

    print_summary(&overall, &groups);
    write_progress(root, &overall, &groups);
    println!("\nWrote PROGRESS.md");
}

fn evaluate(t: &Phpt) -> Outcome {
    let expected = match &t.expect {
        Some(e) => e,
        None if t.has_expectf => return Outcome::Unsupported, // EXPECTF: runner can't grade yet
        None => return Outcome::Unsupported,
    };
    match run(&t.file) {
        Ok(actual) if actual.trim_end() == expected.trim_end() => Outcome::Pass,
        _ => Outcome::Fail,
    }
}

fn pct(part: usize, whole: usize) -> f64 {
    if whole > 0 {
        part as f64 * 100.0 / whole as f64
    } else {
        0.0
    }
}

fn print_summary(overall: &Tally, groups: &BTreeMap<String, Tally>) {
    let [pass, fail, na, total] = *overall;
    let gradeable = pass + fail;

    // Largest areas first.
    let mut sorted: Vec<(&String, &Tally)> = groups.iter().collect();
    sorted.sort_by(|a, b| b.1[3].cmp(&a.1[3]));

    println!("\nBy area (top 30):");
    println!("  {:<22} {:>6} {:>7} {:>7} {:>7}", "area", "pass", "fail", "n/a", "total");
    for (g, t) in sorted.iter().take(30) {
        println!("  {:<22} {:>6} {:>7} {:>7} {:>7}", trunc(g, 22), t[0], t[1], t[2], t[3]);
    }
    if sorted.len() > 30 {
        println!("  …(+{} more areas)", sorted.len() - 30);
    }

    println!("\n====================================");
    println!("PASS {pass}   FAIL {fail}   N/A {na}   TOTAL {total}");
    println!(
        "Pass rate: {pass}/{total} ({:.2}% of all .phpt) | {:.2}% of gradeable ({gradeable})",
        pct(pass, total),
        pct(pass, gradeable),
    );
}

fn write_progress(root: &str, overall: &Tally, groups: &BTreeMap<String, Tally>) {
    let [pass, fail, na, total] = *overall;
    let gradeable = pass + fail;

    let mut md = String::new();
    md.push_str("# FerroPHP — Progress\n\n");
    md.push_str("> Auto-generated by `cargo run`. The whole point of this project is to watch this number climb, in public.\n\n");
    md.push_str("## Scoreboard\n\n");
    md.push_str(&format!(
        "**`.phpt` pass rate: {pass} / {total}  ({:.2}% of the entire PHP test suite)**\n\n",
        pct(pass, total)
    ));
    md.push_str(&format!(
        "_Among tests the runner can currently grade ({gradeable}): {:.2}%. \
         The {na} \"not-yet-gradeable\" tests mostly use `--EXPECTF--`, which the runner doesn't match yet._\n\n",
        pct(pass, gradeable)
    ));
    md.push_str("| ✓ pass | ✗ fail | • not-yet-gradeable | total |\n");
    md.push_str("|---:|---:|---:|---:|\n");
    md.push_str(&format!("| {pass} | {fail} | {na} | {total} |\n\n"));

    md.push_str("## By area\n\n| area | ✓ pass | total | % |\n|---|---:|---:|---:|\n");
    let mut sorted: Vec<(&String, &Tally)> = groups.iter().collect();
    sorted.sort_by(|a, b| b.1[3].cmp(&a.1[3]));
    for (g, t) in &sorted {
        md.push_str(&format!("| `{g}` | {} | {} | {:.1}% |\n", t[0], t[3], pct(t[0], t[3])));
    }

    md.push_str("\n## Roadmap (the climb)\n\n");
    md.push_str(ROADMAP);

    let _ = fs::write(Path::new(root).join("PROGRESS.md"), md);
}

fn parse_phpt(text: &str) -> Phpt {
    let mut sections: Vec<(String, String)> = Vec::new();
    let mut current: Option<String> = None;
    let mut buf = String::new();
    for line in text.lines() {
        if let Some(name) = section_header(line) {
            if let Some(c) = current.take() {
                sections.push((c, std::mem::take(&mut buf)));
            }
            current = Some(name);
        } else if current.is_some() {
            buf.push_str(line);
            buf.push('\n');
        }
    }
    if let Some(c) = current.take() {
        sections.push((c, buf));
    }
    let get = |key: &str| {
        sections
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.clone())
    };
    Phpt {
        file: get("FILE").unwrap_or_default(),
        expect: get("EXPECT"),
        has_expectf: get("EXPECTF").is_some(),
    }
}

/// A section header is a line that is exactly `--NAME--` (uppercase + `_`).
fn section_header(line: &str) -> Option<String> {
    let t = line.trim_end();
    if t.len() > 4 && t.starts_with("--") && t.ends_with("--") {
        let inner = &t[2..t.len() - 2];
        if !inner.is_empty() && inner.chars().all(|c| c.is_ascii_uppercase() || c == '_') {
            return Some(inner.to_string());
        }
    }
    None
}

/// Bucket a corpus test by area, mirroring how PHP itself organises tests.
fn group_of(p: &Path) -> String {
    let s = p.to_string_lossy().replace('\\', "/");
    if let Some(i) = s.find("/ext/") {
        let name = s[i + 5..].split('/').next().unwrap_or("?");
        return format!("ext/{name}");
    }
    if s.contains("/Zend/") {
        return "Zend".to_string();
    }
    if let Some(i) = s.find("/sapi/") {
        let name = s[i + 6..].split('/').next().unwrap_or("?");
        return format!("sapi/{name}");
    }
    "core".to_string()
}

fn collect_phpt(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let p = entry.path();
            if p.is_dir() {
                collect_phpt(&p, out);
            } else if p.extension().map(|e| e == "phpt").unwrap_or(false) {
                out.push(p);
            }
        }
    }
}

fn trunc(s: &str, max: usize) -> String {
    if s.chars().count() <= max {
        s.to_string()
    } else {
        format!("{}…", s.chars().take(max - 1).collect::<String>())
    }
}

const ROADMAP: &str = r#"The ladder to **"WordPress boots in the browser"**. Each rung gets its own slice of real `.phpt` tests as the oracle.

- [x] **v0 — Hello, World.** Inline HTML, `echo`, string/int literals, `.` concat.
- [x] **v1 — Variables & types.** `$vars`, assignment, the zval value model (int/float/bool/null/string), `"$var"` interpolation.
- [x] **v2 — Operators & expressions.** Arithmetic, comparison, logical, precedence, parentheses, float literals, type juggling.
- [ ] **v3 — Control flow.** `if`/`else`, `while`, `for`, `foreach`, `switch`.
- [ ] **v4 — Functions.** User functions, parameters, return, scope.
- [ ] **v5 — Arrays & strings.** PHP arrays (ordered maps) + the core built-ins WordPress leans on.
- [ ] **v6 — Classes.** Classes, interfaces, traits — the OOP WordPress actually uses.
- [ ] **v7 — pcre / mbstring.** Regex + Unicode. (Here be dragons.)
- [ ] **v8 — Request lifecycle.** Superglobals, output buffering, the Playground host interface.
- [ ] **v9 — pdo_sqlite.** WordPress-in-Playground runs on SQLite, not MySQL.
- [ ] **🎯 WordPress boots in the browser** (compiled to WASM, smaller than the Emscripten build).

### Runner TODO
- [ ] `--EXPECTF--` matcher (unlocks grading of thousands more tests)
- [ ] honor `--SKIPIF--` / `--EXTENSIONS--`
"#;
